signal:
  base_path: '/home/crypto/signal/'
  pred_dir: 'predv23_1w'
  money_scale : 1.0

minutes : 3
trade_min : 2
proxy: {http : 'http://127.0.0.1:33881', https : 'http://127.0.0.1:33881'}
timeout : 2
order_hours : [5]
gorder:
    shift: 0.0
    ada_shift_range : 0.0
    max_shift : 5.0
    tcr : 1.0
    expand : [0.0]
    price_normw : 0.9
    money_normw : 1.0
    rwp : 1.0
    trw : 0.5
    predratio : 0.5
    simcnt : 2700
    maxr : 2.5
    minr : 1.0
    trade_succ_ratio : 1.0    
    money_limit_ratio : 10.0
    cancel_delay : 60
    sim_money : 1000
    mr_scale : 0.0
    # bp_map : [0, 1, 2, 3, 4, 5, 7, 10, 15, 20, 30, 40]
    bp_map : [1, 3, 4, 5, 7, 10, 15, 20, 30, 40]
    # bp_map : [5]
    ts : 0.8
    sbp_trhes : 0.25
    mbr_thres : 0.45
    mbrw : 3.0
    bu_ratio : 3.0
    bu_w : 0.18
    tr_exp : 0.2
    simlen : 45
    simdc : 3

    save_order_info_path : "/home/crypto/sec_klines_env/cryptoqt/trade/min3/data/order_info"
    path : "/home/crypto/sec_klines_env/cryptoqt/prm/model_states/infmodel/prmvtest/res/res.h5"

gorder2:
    shift: 0.0
    ada_shift_range : 0.0
    max_shift : 0.0
    tcr : 1.0
    expand : [0.0]
    price_normw : 0.5
    money_normw : 1.0
    avgscale : 1.2
    
    rwp : 0.5
    trw : 3.0
    predratio : 0.5
    simcnt : 1500
    maxr : 10.0
    minr : 0.1
    trade_succ_ratio : 1.0    
    money_limit_ratio : 10.0
    cancel_delay : 3
    sim_money : 1000
    mr_scale : 0.0
    bp_map : [3]
    ts : 0.8
    sbp_trhes : 0.25
    mbr_thres : 0.60
    mbrw : 2.0
    bu_ratio : 3.0
    bu_w : [0.10, 0.15]
    tr_exp : 0.2
    simlen : 150
    simdc : 5
    ucw : 1.2
    sucw : 0.5
    fth : 0.9
    sfth : 1.0
    exceed_ratio : 1.0
    cnt_cravg_shift : 0.1
    bpw : 0.5

    save_order_info_path : "/home/crypto/sec_klines_env/cryptoqt/trade/min3/data/order_info"
    path : "/home/crypto/sec_klines_env/cryptoqt/prm/model_states/infmodel/prmvtest/res/res.h5"

processes:
  - id: 0
    api_key: oaBSzp1IvQpz0jTuAQljotMmEcY0BtbNs6OP7VYxgb1RXCUcG131Miq6UY9bS8ms
    api_secret: x8x6d9GUMLyn7wIoM2oFiT5J8dJPYhtk33AzY7b69vIrkrRvrT572h7nxeh2ps7s