signal:
  base_path: '/home/crypto/signal/'
  pred_dir: 'predv23_1w'
  money_scale : 1.0

minutes : 3
trade_min : 2
proxy: {http : 'http://127.0.0.1:33881', https : 'http://127.0.0.1:33881'}
timeout : 2
order_hours : [5]
gorder:
    splitcnt : 3
    cancel_delay : 5

gorder2:
    splitcnt : 3
    cancel_delay : 5

processes:
  - id: 0
    key : 'qxftbrQhhN5lXboD4bkwhZ3VMJvOIAeQewanOagpptqP5Rb6ZZ9TRKyHIKdGTIkM'
    secret : '7P4DAvpjWeuQpKAfG8ZpXN4J8OkcNrk1Wx4mwJJyeeWaK5yJoxR2He01NPcYO3cJ'