
signal_path : "/home/crypto/signal/predv25_1w"
trade_info_path : "/home/crypto/sec_klines_env/cryptoqt/trade/algo/data/account"
pos_info_path : "/home/crypto/sec_klines_env/cryptoqt/trade/algo/data/pos"
acc_info_path : "/home/crypto/sec_klines_env/cryptoqt/trade/algo/data/accvalue"
save_order_info_path : "/home/crypto/sec_klines_env/cryptoqt/trade/algo/data/order_info"
min_delta : 5
minute_list : [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55]
lookback_mins : 5
log_path : "./logs/costinfo.log"

um_client:
    key : 'SULw1eShlgM3JK5fPGH2In5lQl4YujhQzZMEJnbaeUYzEGQW8OxJu2q5wUak6P65'
    secret : 'GqlJkGbpJX5GSChIhbcTc1Z1bHFagFy95frQcD8dWlJHQdlkOwYtBVca4VNipR8d'
    minmaxcnt : 150
    timeout : 2
    reuse_min : 10
    proxies :
    - {http_proxy : 'http://127.0.0.1:16890', https_proxy : 'http://127.0.0.1:16890'}
    - {http_proxy : 'http://127.0.0.1:17890', https_proxy : 'http://127.0.0.1:17890'}
    - {http_proxy : 'http://127.0.0.1:18890', https_proxy : 'http://127.0.0.1:18890'}
    - {http_proxy : 'http://127.0.0.1:19890', https_proxy : 'http://127.0.0.1:19890'}
    - {http_proxy : 'http://127.0.0.1:20890', https_proxy : 'http://127.0.0.1:20890'}
    - {http_proxy : 'http://127.0.0.1:10890', https_proxy : 'http://127.0.0.1:10890'}
    - {http_proxy : 'http://127.0.0.1:11890', https_proxy : 'http://127.0.0.1:11890'}
    - {http_proxy : 'http://127.0.0.1:12890', https_proxy : 'http://127.0.0.1:12890'}
    - {http_proxy : 'http://127.0.0.1:13890', https_proxy : 'http://127.0.0.1:13890'}
    - {http_proxy : 'http://127.0.0.1:14890', https_proxy : 'http://127.0.0.1:14890'}
    - {http_proxy : 'http://127.0.0.1:15890', https_proxy : 'http://127.0.0.1:15890'}
    - {http_proxy : 'http://127.0.0.1:7890', https_proxy : 'http://127.0.0.1:7890'}
    - {http_proxy : 'http://127.0.0.1:7990', https_proxy : 'http://127.0.0.1:7990'}
    - {http_proxy : 'http://127.0.0.1:8090', https_proxy : 'http://127.0.0.1:8090'}
    - {http_proxy : 'http://127.0.0.1:8190', https_proxy : 'http://127.0.0.1:8190'}
    - {http_proxy : 'http://127.0.0.1:8290', https_proxy : 'http://127.0.0.1:8290'}
    - {http_proxy : 'http://127.0.0.1:8390', https_proxy : 'http://127.0.0.1:8390'}
    - {http_proxy : 'http://127.0.0.1:8490', https_proxy : 'http://127.0.0.1:8490'}
    - {http_proxy : 'http://127.0.0.1:8590', https_proxy : 'http://127.0.0.1:8590'}
    - {http_proxy : 'http://127.0.0.1:8690', https_proxy : 'http://127.0.0.1:8690'}
    - {http_proxy : 'http://127.0.0.1:8790', https_proxy : 'http://127.0.0.1:8790'}
    - {http_proxy : 'http://127.0.0.1:8890', https_proxy : 'http://127.0.0.1:8890'}
    - {http_proxy : 'http://127.0.0.1:5890', https_proxy : 'http://127.0.0.1:5890'}
    - {http_proxy : 'http://127.0.0.1:5900', https_proxy : 'http://127.0.0.1:5900'}
    - {http_proxy : 'http://127.0.0.1:5910', https_proxy : 'http://127.0.0.1:5910'}
    - {http_proxy : 'http://127.0.0.1:5920', https_proxy : 'http://127.0.0.1:5920'}
    - {http_proxy : 'http://127.0.0.1:5930', https_proxy : 'http://127.0.0.1:5930'}
    - {http_proxy : 'http://127.0.0.1:5940', https_proxy : 'http://127.0.0.1:5940'}
    - {http_proxy : 'http://127.0.0.1:5950', https_proxy : 'http://127.0.0.1:5950'}
    - {http_proxy : 'http://127.0.0.1:5960', https_proxy : 'http://127.0.0.1:5960'}
    - {http_proxy : 'http://127.0.0.1:5970', https_proxy : 'http://127.0.0.1:5970'}
    - {http_proxy : 'http://127.0.0.1:5980', https_proxy : 'http://127.0.0.1:5980'}
