
# starttm : 20240929140000
# endtm : 20240929230000

starttm : 20240929130000
endtm : 20240929180000

trade_succ_ratio : 1.0
money_limit_ratio : 10.0

gorder:
    shift: 0.0
    ada_shift_range : 0.0
    max_shift : 3.0
    tcr : 1.0
    expand : [0.0]
    price_normw : 0.9
    money_normw : 1.0
    avgscale : 1.2
    
    rwp : 0.5
    trw : 1.2
    predratio : 0.5
    simcnt : 1500
    maxr : 5.0
    minr : 0.1
    trade_succ_ratio : 1.0    
    money_limit_ratio : 10.0
    cancel_delay : 10
    sim_money : 1000
    mr_scale : 0.0
    # bp_map : [0, 1, 2, 3, 4, 5, 7, 10, 15, 20, 30, 40]
    # bp_map : [0, 1, 3,  5, 7, 10]
    bp_map : [3]
    ts : 0.8
    sbp_trhes : 0.25
    mbr_thres : 0.60
    mbrw : 2.0
    bu_ratio : 3.0
    bu_w : [0.10, 0.2]
    tr_exp : 0.2
    simlen : 120
    simdc : 5
    ucw : 1.5
    sucw : 0.5
    fth : 1.1
    sfth : 1.2
    exceed_ratio : 1.0
    cnt_cravg_shift : 0.2
    bpw : 0.5
    
    # rwp : 1.1
    # trw : 0.3
    # predratio : 0.5
    # simcnt : 2700
    # maxr : 2.0
    # minr : 0.6
    # trade_succ_ratio : 1.0    
    # money_limit_ratio : 10.0
    # cancel_delay : 30
    # sim_money : 1000
    # mr_scale : 0.0
    # # bp_map : [0, 1, 2, 3, 4, 5, 7, 10, 15, 20, 30, 40]
    # bp_map : [1,  3,  5]
    # # bp_map : [5]
    # ts : 0.8
    # sbp_trhes : 0.35
    # mbr_thres : 0.55
    # mbrw : 2.0
    # bu_ratio : 3.0
    # bu_w : 0.08
    # tr_exp : 0.2
    # simlen : 60
    # simdc : 3
    # ucw : 1.2

    save_order_info_path : "/home/crypto/sec_klines_env/cryptoqt/bsim/data/order_info.h5"
    path : "/home/crypto/sec_klines_env/cryptoqt/prm/model_states/infmodel/prmvtest/res/res.h5"
